version: 0.2

phases:
  build:
    commands:
      - ls -d */
      - echo $partition
      - echo $target
      - for dir in `ls -d */`; do aws s3 cp $dir s3://$target/$partition/$dir --recursive; done