AWSTemplateFormatVersion: 2010-09-09
Description: >
  Create an edge function that can be associated with a cloud front distribution. This is separate from
  the cloud front distro at the moment as the bucket name needs to be hard coded as it cannot be injected
  via environment vars due to edge function restrictions.

Parameters:
  CodeBucketName:
    Type: String
    Description: Bucket containing lambda code zip file

Resources:
  EdgeProtoVersion:
    Type: "AWS::Lambda::Version"
    DependsOn: EdgeProto
    Properties:
      FunctionName: !Ref EdgeProto
      Description: "Edge deployable proto function"

  EdgeProto:
    Type: "AWS::Lambda::Function"
    Properties:
      Handler: "router.blue"
      Role: !GetAtt LambdaExecutionRole.Arn
      Code: 
        S3Bucket: !Ref CodeBucketName
        S3Key: router.zip
      Runtime: "nodejs8.10"

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
            - edgelambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: logs
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:*
            Resource: arn:aws:logs:*:*:*

Outputs:
    LambdaArn:
        Value: !GetAtt EdgeProto.Arn

    LambdaVersion:
        Value: !Ref EdgeProtoVersion